### ISSUE TITLE
Remove TODO Headers from README

### ISSUE THREAD

**Issue by kylecesmat** [FormidableLabs/formidable-playbook#24]
We should remove this TODO copy as it adds clutter to the home page in its current form. We will ensure that any notes for these todos are moved into issues.

**Comment by ryan-roemer** [comment]
Just convert the text into HTML comments so that we can search and find on the to do's for the sections and then they won't  appear  in the rendered markdown

**Comment by kylecesmat** [comment]
Right! I'll do that
