### ISSUE TITLE
Links to example code files don't work on production site

### ISSUE THREAD

**Issue by bmathews** [FormidableLabs/formidable-playbook#29]

**Comment by paulathevalley** [comment]
@bmathews Are the links this issue is referring to on this page? (foo.js, app1.js, app2.js) https://formidable.com/open-source/playbook/frontend/webpack-code-splitting/

**Comment by bmathews** [comment]
Yep! 

![image](https://cloud.githubusercontent.com/assets/848347/17867527/b6f58ef6-685f-11e6-950c-d69dd9174085.png)

**Comment by coopy** [comment]
Solution: Make the links absolute.

**Comment by ryan-roemer** [comment]
Actually, after we retrofit the repo back to what it was with docs at root and _serve_ the root, the examples become part of the servable portion and everything magically works 😉 

The problem right now is the `examples/` don't exist **at all** in the lander site AFAICT

**Comment by coopy** [comment]
We have deployed a new version of the site that publishes the `examples/` directory. The remaining problem is that the static site generator plugin publishes the nested markdown files into a directory structure like:

```
├── docs
│   ├── frontend
│   │   ├── webpack-code-splitting
│   │   │   └── index.html
```

This breaks the relative links from `docs/frontend/webpack-code-splitting.md` to e.g. `../../examples/frontend/src/app2.js`

We could configure the static generator to spit out `webpack-code-splitting.html` files (without the subdir) but that will not play nicely with the React Routes.

Strawman idea: Make the `formidable-playbook` markdown file structure match what's expected in the `formidable-playbook-lander` project:
`docs/frontend/webpack-code-splitting.md -> docs/frontend/webpack-code-splitting/index.md`
